name: 打包几何计算器-win

on:
  workflow_dispatch:
    inputs:
      version:
        description: '版本'
        required: true

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: 建立Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install nuitka

      - name: 用Nuitka编译
        run: |
          nuitka --standalone --mingw64 --enable-plugin=pyqt6,matplotlib --windows-disable-console --lto=no --remove-output --assume-yes-for-download --product-name=几何计算器 --output-dir=out --file-version=${{ github.event.inputs.version }} --product-version=${{ github.event.inputs.version }} --file-description=几何计算器 --copyright="Copyright MC着火的冰块. All right reserved." --show-progress --show-memory --nofollow-import-to=Pillow,PIL,numpy --include-data-file=./interfaces/help.md=./interfaces/help.md main.py -o GeometryCalculator.exe

      - name: 上传编译好的文件
        uses: actions/upload-artifact@v2
        with:
          name: GeometryCalculator-v${{ github.event.inputs.version }}-win
          path: out/main.dist/
